spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create-drop

    datasource:
        url: jdbc:mysql://localhost:3306/springbootdb_test
        username: maykowski
        password: '!@#alicia123'
        driver-class-name: com.mysql.jdbc.Driver

#    profiles: test